//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseballapp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stadium
    {
        public int StadiumID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Surface { get; set; }
        public string Capacity { get; set; }
        public string Team { get; set; }
        public string Typology { get; set; }
        public string CenterField { get; set; }
        public string LogoPic { get; set; }
        public string StadiumPic { get; set; }
    }
}
